name: Publish package to pub.dev
on:
  push:
    branches:   
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup credentials
      run: | 
        mkdir -p ~/.pub-cache 
        cat <<EOF > ~/.pub-cache/credentials.json
        ${{secrets.PUB_CREDENTIAL_JSON}}
        EOF
    - name: Publish package
      run: pub publish -f
